version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Guga1957!
      MYSQL_DATABASE: images
      MYSQL_PASSWORD: Guga1957!

  app_multithread:
    build: .
    container_name: app_multithread
    depends_on:
      - mysql
    restart: always
    ports:
      - "8081:8080"
